AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-naip-tile-server

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 1024

Parameters:
  ImageFormat:
    Type: String
    Description: Image format tiles will be returned in
    AllowedValues:
      - JPEG
      - PNG
    Default: PNG
  MaxZoom:
    Type: Number
    Description: Max zoom level API will return tiles for
    Default: 20
  MinZoom:
    Type: Number
    Description: Min zoom level API will return tiles for
    Default: 10
  DownscaleMaxZoom:
    Type: Number
    Description: Max zoom level where attempts to create missing tile from downscaling will kick in
    Default: 11
  UpscaleMinZoom:
    Type: Number
    Description: Min zoom level where attempts to create missing tile from upscaling will kick in
    Default: 18
  RescalingEnabled:
    Type: String
    Description: Create missing tiles by rescaling cached tiles
    AllowedValues:
      - "TRUE"
      - "FALSE"
    Default: "TRUE"
  TileCacheBucket:
    Type: String
    Description: Name of S3 bucket to be used as tile cache
    Default: none

Resources:
  NAIPLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'

  NAIPApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "Access-Control-Allow-Origin"
          - "Content-Type"
          - "X-Requested-With"
        AllowMethods:
          - GET
          - OPTIONS

  UtilsLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: makefile

  NAIPTileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: get-naip-tile
      Role: !GetAtt NAIPLambdaRole.Arn
      CodeUri: src/lambda_functions/
      Handler: get_naip_tile.handler
      Layers:
        - !Ref UtilsLambdaLayer
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        NAIPTileHttp:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tile/{year}/{z}/{y}/{x}
            Method: get
            ApiId: !Ref NAIPApi
      Environment:
        Variables:
          IMAGE_FORMAT: !Ref ImageFormat
          MAX_ZOOM: !Ref MaxZoom
          MIN_ZOOM: !Ref MinZoom
          DOWNSCALE_MAX_ZOOM: !Ref DownscaleMaxZoom
          UPSCALE_MIN_ZOOM: !Ref UpscaleMinZoom
          RESCALING_ENABLED: !Ref RescalingEnabled
          TILE_CACHE_BUCKET: !Ref TileCacheBucket

Outputs:
  NAIPTileApi:
    Description: "API Gateway endpoint URL for Prod stage for NAIPTileFunction"
    Value: !Sub "https://${NAIPApi}.execute-api.${AWS::Region}.amazonaws.com/prod/tile"
  NAIPTileFunction:
    Description: "NAIPTileFunction Lambda Function ARN"
    Value: !GetAtt NAIPTileFunction.Arn
  NAIPLambdaIamRole:
    Description: "NAIPLambdaRole ARN"
    Value: !GetAtt NAIPLambdaRole.Arn
  ImageFormat:
    Description: "ImageFormat"
    Value: !Ref ImageFormat
  DownscaleMaxZoom:
    Description: "DownscaleMaxZoom"
    Value: !Ref DownscaleMaxZoom
  UpscaleMinZoom:
    Description: "UpscaleMinZoom"
    Value: !Ref UpscaleMinZoom
  RescalingEnabled:
    Description: "RescalingEnabled"
    Value: !Ref RescalingEnabled
  TileCacheBucket:
    Description: "TileCacheBucket"
    Value: !Ref TileCacheBucket
  MinZoom:
    Description: "MinZoom"
    Value: !Ref MinZoom
  MaxZoom:
    Description: "MaxZoom"
    Value: !Ref MaxZoom
